stateDiagram-v2
  state "Green Light" as GREEN_LIGHT_STATE
  state "Red Light" as RED_LIGHT_STATE
state "Yellow Light" as YELLOW_LIGHT_ STATE


  [*] --> GREEN_LIGHT_STATE
  GREEN_LIGHT_STATE --> YELLOW_LIGHT_STATE: Button pressed
YELLOW_LIGHT_STATE --> RED_LIGHT_STATE: After 3 seconds
  RED_LIGHT_STATE --> GREEN_LIGHT_STATE: Timer > 5 seconds
